"""Add visit_count column to links

Revision ID: da8d791dddfc
Revises: 5a96c7b5f82a
Create Date: 2024-11-01 05:01:50.239758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8d791dddfc'
down_revision = '5a96c7b5f82a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_visits', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_column('max_visits')
        batch_op.drop_column('visit_count')

    # ### end Alembic commands ###
